// <auto-generated />
namespace Lisa.Bioshock.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class ProjectMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProjectMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201312111110269_ProjectMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
